### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by aschweig** [maphi/worksample1#1]
I'd like to try something similar to what you show in this worksample.

Is there a license that this is available under? For example, BSD-2 and BSD-3, Apache License 2.0 or  MIT license?

I have a similar question for your EasyDerive code.  Can that be added here as a repo with a license?

**Comment by maphi** [comment]
Hey @aschweig, i've added Apache License 2.0 in both. You can find the EasyDerive code in the `blog` repo.
